name: Create Draft Release

on:
  push:
    branches: [latest]
  pull_request: # required for autolabeler
    branches: [latest]
    types: [opened, reopened, synchronize, ready_for_review, review_requested]
  workflow_dispatch:

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.date.outputs.date }}
          release_name: ${{ steps.date.outputs.date }}
          body: |
            Homebridge Docker Package Manifest

            | Package | Version |
            |:-------:|:-------:|
            |Ubuntu|24.04|
            |NodeJS| *.*.* |
            |Homebridge-Config-UI-X| *.*.* |
            |Homebridge| latest * |
            |ffmpeg for homebridge| *.*.* |

            * Note: Homebridge is only updated to latest on a new installation, refreshing an existing installation does not update Homebridge version.  To update the Homebridge version please use the UI.
          draft: true
          prerelease: false
